server:
  port: 8088
spring:
  dataSource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    #url: jdbc:shardingsphere:classpath:ss-config-standard.yaml
    url: jdbc:shardingsphere:classpath:ss-config-complex.yaml
mybatis:
  config-location: classpath:mybatis-config.xml